### ISSUE TITLE
Prevent new players from joining

### ISSUE THREAD

**Issue by leviem1** [CrimsonWarpedcraft/UHC#14]
Prevent new players from joining the game after the game is started. This will consist of a few parts:
- [x] Create a HashSet inside of the GameState class that will store all players in the game.
- [x] Create a storeGamePlayers() method in GameState, store all online players in that Set if the input is true.
- [x] Create a getGamePlayers() method which returns a copy of the HashSet (it has to be a copy otherwise the code that uses it could accidentally modify the data)
- [x] Create a method in GameState named isGamePlayer() to search if a Player is in the Set.
- [x] Create a listener to check if a Player from a PlayerJoinEvent is in the list of online players when the game is running.

**Comment by leviem1** [comment]
@zupmine updated the issue for you

**Comment by zupmine** [comment]
@leviem1 Tests Required

**Comment by leviem1** [comment]
Turns out you can't store objects of Players after they've logged out. Working on a solution with UUIDs which are basically a more unique id than usernames
